<?xml version="1.0" encoding="UTF-8"?><testsuite failures="7" name="cucumber.runtime.formatter.JUnitFormatter" skipped="0" tests="12" time="347.26913">
<testcase classname="Test apply to job functionality" name="Check apply now functionality" time="50.762288">
<system-out><![CDATA[Given user has selected a job...............................................passed
When user clicks on apply now...............................................passed
And enters valid data.......................................................passed
Then application is submitted...............................................passed
]]></system-out>
</testcase>
<testcase classname="Test apply to job functionality" name="Check submission on invalid mobile number" time="26.311436">
<failure message="java.lang.AssertionError: expected [true] but found [false]&#13;&#10;&#9;at org.testng.Assert.fail(Assert.java:96)&#13;&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:776)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:44)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:54)&#13;&#10;&#9;at stepDefinition.ApplicationStepDef.error_is_displyed(ApplicationStepDef.java:106)&#13;&#10;&#9;at ✽.And invalid phone number is displyed(src/test/resources/Features/Application.feature:16)&#13;&#10;"><![CDATA[Given user has selected a job...............................................passed
And clicked on apply now....................................................passed
When user enters an invalid 1234567890......................................passed
Then user clicks on submit button...........................................passed
And invalid phone number is displyed........................................failed

StackTrace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at stepDefinition.ApplicationStepDef.error_is_displyed(ApplicationStepDef.java:106)
	at ✽.And invalid phone number is displyed(src/test/resources/Features/Application.feature:16)
]]></failure>
</testcase>
<testcase classname="Test apply to job functionality" name="Check submission on invalid mobile number 2" time="27.094356">
<failure message="java.lang.AssertionError: expected [true] but found [false]&#13;&#10;&#9;at org.testng.Assert.fail(Assert.java:96)&#13;&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:776)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:44)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:54)&#13;&#10;&#9;at stepDefinition.ApplicationStepDef.error_is_displyed(ApplicationStepDef.java:106)&#13;&#10;&#9;at ✽.And invalid phone number is displyed(src/test/resources/Features/Application.feature:16)&#13;&#10;"><![CDATA[Given user has selected a job...............................................passed
And clicked on apply now....................................................passed
When user enters an invalid 2345678901......................................passed
Then user clicks on submit button...........................................passed
And invalid phone number is displyed........................................failed

StackTrace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at stepDefinition.ApplicationStepDef.error_is_displyed(ApplicationStepDef.java:106)
	at ✽.And invalid phone number is displyed(src/test/resources/Features/Application.feature:16)
]]></failure>
</testcase>
<testcase classname="Test apply to job functionality" name="Check submission on invalid mobile number 3" time="29.335146">
<system-out><![CDATA[Given user has selected a job...............................................passed
And clicked on apply now....................................................passed
When user enters an invalid 7234567890......................................passed
Then user clicks on submit button...........................................passed
And invalid phone number is displyed........................................passed
]]></system-out>
</testcase>
<testcase classname="Test apply to job functionality" name="Check submission on invalid location" time="24.947144">
<failure message="java.lang.AssertionError: expected [true] but found [false]&#13;&#10;&#9;at org.testng.Assert.fail(Assert.java:96)&#13;&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:776)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:44)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:54)&#13;&#10;&#9;at stepDefinition.ApplicationStepDef.location_is_not_valid_message_is_displayed(ApplicationStepDef.java:128)&#13;&#10;&#9;at ✽.And Location is not valid message is displayed(src/test/resources/Features/Application.feature:29)&#13;&#10;"><![CDATA[Given user has selected a job...............................................passed
And clicked on apply now....................................................passed
When user enters invalid as ()*&............................................passed
Then user clicks on submit button...........................................passed
And Location is not valid message is displayed..............................failed

StackTrace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at stepDefinition.ApplicationStepDef.location_is_not_valid_message_is_displayed(ApplicationStepDef.java:128)
	at ✽.And Location is not valid message is displayed(src/test/resources/Features/Application.feature:29)
]]></failure>
</testcase>
<testcase classname="Test apply to job functionality" name="Check submission on invalid location 2" time="28.296561">
<failure message="java.lang.AssertionError: expected [true] but found [false]&#13;&#10;&#9;at org.testng.Assert.fail(Assert.java:96)&#13;&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:776)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:44)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:54)&#13;&#10;&#9;at stepDefinition.ApplicationStepDef.location_is_not_valid_message_is_displayed(ApplicationStepDef.java:128)&#13;&#10;&#9;at ✽.And Location is not valid message is displayed(src/test/resources/Features/Application.feature:29)&#13;&#10;"><![CDATA[Given user has selected a job...............................................passed
And clicked on apply now....................................................passed
When user enters invalid as 12345...........................................passed
Then user clicks on submit button...........................................passed
And Location is not valid message is displayed..............................failed

StackTrace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at stepDefinition.ApplicationStepDef.location_is_not_valid_message_is_displayed(ApplicationStepDef.java:128)
	at ✽.And Location is not valid message is displayed(src/test/resources/Features/Application.feature:29)
]]></failure>
</testcase>
<testcase classname="Test apply to job functionality" name="Check submission on invalid location 3" time="27.169734">
<failure message="java.lang.AssertionError: expected [true] but found [false]&#13;&#10;&#9;at org.testng.Assert.fail(Assert.java:96)&#13;&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:776)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:44)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:54)&#13;&#10;&#9;at stepDefinition.ApplicationStepDef.location_is_not_valid_message_is_displayed(ApplicationStepDef.java:128)&#13;&#10;&#9;at ✽.And Location is not valid message is displayed(src/test/resources/Features/Application.feature:29)&#13;&#10;"><![CDATA[Given user has selected a job...............................................passed
And clicked on apply now....................................................passed
When user enters invalid as Aba/123.........................................passed
Then user clicks on submit button...........................................passed
And Location is not valid message is displayed..............................failed

StackTrace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at stepDefinition.ApplicationStepDef.location_is_not_valid_message_is_displayed(ApplicationStepDef.java:128)
	at ✽.And Location is not valid message is displayed(src/test/resources/Features/Application.feature:29)
]]></failure>
</testcase>
<testcase classname="Test apply to job functionality" name="Check submission on invalid location 4" time="27.309815">
<system-out><![CDATA[Given user has selected a job...............................................passed
And clicked on apply now....................................................passed
When user enters invalid as Aurangabad......................................passed
Then user clicks on submit button...........................................passed
And Location is not valid message is displayed..............................passed
]]></system-out>
</testcase>
<testcase classname="Test apply to job functionality" name="Check submission on invalid relevant experience" time="26.383271">
<failure message="java.lang.AssertionError: expected [true] but found [false]&#13;&#10;&#9;at org.testng.Assert.fail(Assert.java:96)&#13;&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:776)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:44)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:54)&#13;&#10;&#9;at stepDefinition.ApplicationStepDef.invalid_relative_experience_message_should_be_displayed(ApplicationStepDef.java:150)&#13;&#10;&#9;at ✽.And Invalid relative experience message should be displayed(src/test/resources/Features/Application.feature:43)&#13;&#10;"><![CDATA[Given user has selected a job...............................................passed
And clicked on apply now....................................................passed
When user enters invalid the100.............................................passed
Then user clicks on submit button...........................................passed
And Invalid relative experience message should be displayed.................failed

StackTrace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at stepDefinition.ApplicationStepDef.invalid_relative_experience_message_should_be_displayed(ApplicationStepDef.java:150)
	at ✽.And Invalid relative experience message should be displayed(src/test/resources/Features/Application.feature:43)
]]></failure>
</testcase>
<testcase classname="Test apply to job functionality" name="Check submission on invalid relevant experience 2" time="26.457962">
<system-out><![CDATA[Given user has selected a job...............................................passed
And clicked on apply now....................................................passed
When user enters invalid the0...............................................passed
Then user clicks on submit button...........................................passed
And Invalid relative experience message should be displayed.................passed
]]></system-out>
</testcase>
<testcase classname="Test apply to job functionality" name="Check submission on invalid relevant experience 3" time="25.897382">
<failure message="java.lang.AssertionError: expected [true] but found [false]&#13;&#10;&#9;at org.testng.Assert.fail(Assert.java:96)&#13;&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:776)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:44)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:54)&#13;&#10;&#9;at stepDefinition.ApplicationStepDef.invalid_relative_experience_message_should_be_displayed(ApplicationStepDef.java:150)&#13;&#10;&#9;at ✽.And Invalid relative experience message should be displayed(src/test/resources/Features/Application.feature:43)&#13;&#10;"><![CDATA[Given user has selected a job...............................................passed
And clicked on apply now....................................................passed
When user enters invalid the21..............................................passed
Then user clicks on submit button...........................................passed
And Invalid relative experience message should be displayed.................failed

StackTrace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at stepDefinition.ApplicationStepDef.invalid_relative_experience_message_should_be_displayed(ApplicationStepDef.java:150)
	at ✽.And Invalid relative experience message should be displayed(src/test/resources/Features/Application.feature:43)
]]></failure>
</testcase>
<testcase classname="Test apply to job functionality" name="Check submission on invalid relevant experience 4" time="27.304035">
<system-out><![CDATA[Given user has selected a job...............................................passed
And clicked on apply now....................................................passed
When user enters invalid the5...............................................passed
Then user clicks on submit button...........................................passed
And Invalid relative experience message should be displayed.................passed
]]></system-out>
</testcase>
</testsuite>
